title:            Rangers Soccer Academy
# description:      Describe your website here.
reading_time:     false
comments:         false
show_search: false
words_per_minute: 200
logo:             images/logo.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://rangerssocceracademy.com

menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
    submenu:
      - title: 'Introduction'
        url: '/about'
      - title: 'Curriculum'
        url: '/about/curriculum'
      - title: 'Gers Rules'
        url: '/about/gers-rules'
      - title: 'Code of Conduct'
        url: '/about/conduct'
  - title: 'Gallery'
    url: '/gallery'
  - title: 'Homework'
    url: '/hw'
  - title: 'Links'
    url: '/links'
  - title: 'Contact'
    url: '/contact'

# Owner/author information
owner:
  name:           Rangers Soccer Academy
  # site:           http://aronbordin.com
  # avatar:         images/avatar.jpg
  # bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  # email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  # twitter: aron_bordin
  # facebook:
  # github: aron-bordin
  # stackexchange:
  # linkedin:
  # instagram:
  # flickr:
  # tumblr:
  # google plus id, include the '+', eg +AronBordin
  # google_plus:    +yourid

# social:
#   - title: "github"
#     url: "https://github.com/aron-bordin"
#   - title: "linkedin"
#     url: "https://br.linkedin.com/in/aronbordin"
#   - title: "youtube"
#     url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background: rangers_tartan.gif

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
